# Generated by Django 6.0 on 2026-01-29 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2026, 1, 29, 7, 22, 1, 811222, tzinfo=datetime.timezone.utc))),
                ('likes', models.IntegerField(default=0)),
                ('image', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
