# Generated by Django 6.0 on 2026-01-29 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 29, 7, 31, 24, 492879, tzinfo=datetime.timezone.utc)),
        ),
    ]
